Update ysf-clients scripts

diff --git a/mmdvm-host/files/etc/init.d/mmdvmhost.init b/mmdvm-host/files/etc/init.d/mmdvmhost.init
--- a/mmdvm-host/files/etc/init.d/mmdvmhost.init
+++ b/mmdvm-host/files/etc/init.d/mmdvmhost.init
@@ -6,24 +6,30 @@ START=99
 SERVICE_USE_PID=0
 
 USER=mmdvm
+PKG_NAME=MMDVMHost
+BIN_FILE=/usr/sbin/MMDVMHost
+CONF_FILE=/etc/MMDVM.ini
+PID_FILE=/tmp/mmdvmhost.pid
 
 do_start() {
         #mkdir -m 0755 -p /var/log/mmdvm
 
         #check mmdvm user and fix the tty permission
         if id "${USER}" >/dev/null 2>&1; then
+                echo "user check ok"
                 [ -e /dev/ttyACM0 ] && chown mmdvm /dev/ttyACM0 && echo "ttyACM0 found and fixed"
         else
                 echo "user ${USER} does not exist, MMDVMHost will not start." && exit;
         fi
 
         #echo "Starting MMDVM Host"
-        if [ -e /etc/MMDVM.ini ]; then
-                /usr/sbin/MMDVMHost /etc/MMDVM.ini
-                echo $! >/tmp/mmdvmhost.pid
-                >&2 echo "MMDVMHost started"
+        if [ -e ${CONF_FILE} ]; then
+                ${BIN_FILE} ${CONF_FILE}
+                PID=`pidof ${PKG_NAME}`
+                echo ${PID} >${PID_FILE}
+                >&2 echo "${PKG_NAME} started"
         else
-                >&2 echo "configuration file missing, MMDVMHost will not start."
+                >&2 echo "configuration file missing, ${PKG_NAME} will not start."
         fi
 }
 
@@ -32,13 +38,13 @@ start() {
 }
 
 stop() {
-	if [ -e /tmp/mmdvmhost.pid ]; then
-		PID=`cat /tmp/mmdvmhost.pid`
+	if [ -e ${PID_FILE} ]; then
+		PID=`cat ${PID_FILE}`
 		kill $PID > /dev/null 2>&1
-		rm -f /tmp/mmdvmhost.pid
-		echo "MMDVM Host stopped"
+		rm -f ${PID_FILE}
+		echo "${PKG_NAME} stopped"
 	else
-		echo "MMDVM Host is not running"
+		echo "${PKG_NAME} is not running"
 	fi
     return 0
 }
