Fix mmdvm-host init script

diff --git a/mmdvm-host/files/etc/init.d/mmdvmhost.init b/mmdvm-host/files/etc/init.d/mmdvmhost.init
--- a/mmdvm-host/files/etc/init.d/mmdvmhost.init
+++ b/mmdvm-host/files/etc/init.d/mmdvmhost.init
@@ -15,6 +15,7 @@ CONF_NAME=MMDVM.ini
 CONF_FILE=/etc/${CONF_NAME}
 TMP_CONF_FILE=/tmp/.MMDVM.ini.upd
 PID_FILE=/tmp/mmdvmhost.pid
+LOG_DIR=/var/log/mmdvm
 MD5_TOOL='/usr/bin/openssl md5'
 SERVER_URL='https://hamclub.net/openwrt/config'
 
@@ -63,16 +64,16 @@ do_update(){
 
 check_update() {
   echo "Updating config from network..."
-  i=0
+  i=1
   if [ $1 -eq 0 ];then
-    $1=5
+    $1=3
   fi
 
   while [ $i -le $1 ];do
     i=$(($i+1))
+    echo "Trying $(($i-1))...";
     do_update
     if [ $? -ne 0 ];then
-      echo "Retring $i...";
       sleep 5
     else
       return 0
@@ -81,31 +82,60 @@ check_update() {
   return 1
 }
 
-do_start() {
-        # check if service is running
-        if [ -e ${PID_FILE} ]; then
-                PID=`pidof ${PKG_NAME}`
-                if [ $PID -ne 0 ]; then
-                        echo "${PKG_NAME} is running"
-                        return 0
-                fi
+check_user(){
+  id "${USER}" >/dev/null 2>&1
+  if [ $? -eq 1 ]; then
+    if [ -f /usr/sbin/useradd ]; then
+      echo "Creating user ${USER}"
+      /usr/sbin/useradd -N -M -s /bin/false ${USER}
+    else
+      echo "create user ${USER} failed, ${PKG_NAME} will not start." && exit 1;
+    fi
+  fi
+  echo "Check user OK"
+  check_permission
+}
+
+check_permission(){
+  [ -f /dev/ttyACM0 ] && chown ${USER} /dev/ttyACM0 && echo "ttyACM0 found and fixed";
+  [ -f /dev/ttyUSB0 ] && chown ${USER} /dev/ttyUSB0 && echo "ttyUSB0 found and fixed";
+  [ -f /dev/ttyS1 ] && chown ${USER} /dev/ttyS1 && echo "ttyS1 found and fixed";
+  
+  if [ ! -d ${LOG_DIR} ]; then
+    mkdir -m 755 -p ${LOG_DIR}
+  fi
+  chown -R ${USER} ${LOG_DIR}
+  echo "Check permission OK"
+}
+
+check_running(){
+  # check if service is running
+  if [ -e ${PID_FILE} ]; then
+        PID=`pidof ${PKG_NAME}`
+        if [ $? -eq 0 ]; then
+                echo "${PKG_NAME} is running"
+                return 0
         fi
+  fi
+  return 1
+}
 
-        #mkdir -m 0755 -p /var/log/mmdvm
-
-        #check mmdvm user and fix the tty permission
-        if id "${USER}" >/dev/null 2>&1; then
-                echo "user check ok"
-                [ -e /dev/ttyACM0 ] && chown ${USER} /dev/ttyACM0 && echo "ttyACM0 found and fixed"
-                [ -e /dev/ttyS1 ] && chown ${USER} /dev/ttyS1 && echo "ttyS1 found and fixed"
-        else
-                echo "user ${USER} does not exist, ${PKG_NAME} will not start." && exit;
+do_start() {
+        check_running
+        if [ $? -eq 0 ]; then
+          return 0
         fi
 
         #echo "Starting MMDVM Host"
         if [ -e ${CONF_FILE} ]; then
                 ${BIN_FILE} ${CONF_FILE}
+                sleep 3
                 PID=`pidof ${PKG_NAME}`
+                if [ $? -eq 1 ]; then
+                    echo "Process does not exist, ${PKG_NAME} will not start."
+                    #rm ${CONF_FILE}
+                    exit 1
+                fi
                 echo ${PID} >${PID_FILE}
                 >&2 echo "${PKG_NAME} started"
         else
@@ -114,7 +144,15 @@ do_start() {
 }
 
 start() {
-        check_update 5
+        check_running
+        if [ $? -eq 0 ]; then
+          #echo "${PKG_NAME} is running"
+          return 0
+        fi
+
+        check_update 3
+        #check mmdvm user and fix the tty permission
+        check_user        
         do_start
 }
 
