Update init scripts to check user and fix permissions

diff --git a/p25-clients/files/etc/init.d/p25gateway.init b/p25-clients/files/etc/init.d/p25gateway.init
--- a/p25-clients/files/etc/init.d/p25gateway.init
+++ b/p25-clients/files/etc/init.d/p25gateway.init
@@ -11,21 +11,63 @@ PKG_NAME=P25Gateway
 BIN_FILE=/usr/sbin/P25Gateway
 CONF_FILE=/etc/P25Gateway.ini
 PID_FILE=/tmp/p25gateway.pid
+LOG_DIR=/var/log/mmdvm
+
+check_user(){
+  id "${USER}" >/dev/null 2>&1
+  if [ $? -eq 1 ]; then
+    if [ -f /usr/sbin/useradd ]; then
+      echo "Creating user ${USER}"
+      /usr/sbin/useradd -N -M -s /bin/false ${USER}
+    else
+      echo "create user ${USER} failed, ${PKG_NAME} will not start." && exit 1;
+    fi
+  fi
+  echo "Check user OK"
+  check_permission
+}
+
+check_permission(){
+  [ -f /dev/ttyACM0 ] && chown ${USER} /dev/ttyACM0 && echo "ttyACM0 found and fixed";
+  [ -f /dev/ttyUSB0 ] && chown ${USER} /dev/ttyUSB0 && echo "ttyUSB0 found and fixed";
+  [ -f /dev/ttyS1 ] && chown ${USER} /dev/ttyS1 && echo "ttyS1 found and fixed";
+  
+  if [ ! -d ${LOG_DIR} ]; then
+    mkdir -m 755 -p ${LOG_DIR}
+  fi
+  chown -R ${USER} ${LOG_DIR}
+  echo "Check permission OK"
+}
+
+check_running(){
+  # check if service is running
+  if [ -e ${PID_FILE} ]; then
+        PID=`pidof ${PKG_NAME}`
+        if [ $? -eq 0 ]; then
+                echo "${PKG_NAME} is running"
+                return 0
+        fi
+  fi
+  return 1
+}
 
 do_start() {
-        #mkdir -m 0755 -p /var/log/mmdvm
-
-        #check mmdvm user
-        if id "${USER}" >/dev/null 2>&1; then
-                echo "user check ok"
-        else
-                echo "user ${USER} does not exist, ${PKG_NAME} will not start." && exit;
+        check_running
+        if [ $? -eq 0 ]; then
+          return 0
         fi
 
-        #echo "Starting ${PKG_NAME}"
+        #echo "Starting MMDVM Host"
         if [ -e ${CONF_FILE} ]; then
                 ${BIN_FILE} ${CONF_FILE}
+                echo "Starting..."
+                sleep 3
                 PID=`pidof ${PKG_NAME}`
+                if [ $? -eq 1 ]; then
+                    echo "Process does not exist, ${PKG_NAME} will not start."
+                    #rm ${CONF_FILE}
+                    exit 1
+                fi
                 echo ${PID} >${PID_FILE}
                 >&2 echo "${PKG_NAME} started"
         else
@@ -34,7 +76,13 @@ do_start() {
 }
 
 start() {
-	do_start
+	check_running
+        if [ $? -eq 0 ]; then
+          return 0
+        fi
+        #check_update 3
+        check_user        
+        do_start
 }
 
 stop() {
